import React from 'react'
import styles from './styles.module.css'
import Text from './components/Text'
import Password from './components/Password'
import Date from './components/Date'
import Time from './components/Time'
import Email from './components/Email'
import Numeric from './components/Numeric'
import Alphanumeric from './components/Alphanumeric'
import Phone from './components/Phone'
import Checkbox from './components/Checkbox'
import Radiobutton from './components/Radiobutton'
import Textarea from './components/Textarea'

export  { Text, Password, Numeric, Alphanumeric, Email, Date, Time, Phone, Checkbox, Radiobutton, Textarea}
